deb_capstone:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: wizeline-deb
      dataset: movie_analytics
      location: US
      method: oauth
      token: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      job_retries: 1
      threads: 12