name: |
    Retag and Push Airflow Image and Update Values File in 
    the Infrastructure Repository

on:
    pull_request:
      branches:
        - main
      types:
        - closed

env:
    PROJECT_ID: wizeline-deb
    GAR_LOCATION: us-central1
    REPOSITORY: deb-capstone-airflow-gke
    IMAGE: airflow2.7.1-custom

jobs:
  retag_and_push:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    permissions:
        contents: 'read'
        id-token: 'write'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            token_format: 'access_token'
            # Replace with values based on setup.sh in dev-infrastructure repo
            workload_identity_provider: 'projects/734911192367/locations/global/workloadIdentityPools/deb-pool/providers/github-actions'
            service_account: 'deb-sa@wizeline-deb.iam.gserviceaccount.com'
      
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      - name: Retag Docker Image
        run: |
            echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
            docker pull "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_HEAD_REF"
            docker tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_HEAD_REF" "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$SHORT_SHA"
            docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$SHORT_SHA"
      
      # Clone the infrastructure repository and change directory to it
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: 'uche-madu/deb-infrastructure'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          sparse-checkout: |
            terraform/airflow-helm-values/values-dev.yaml
          sparse-checkout-cone-mode: false

      - name: Update values.yaml in Airflow Helm Chart 
        run: |
            sed -i "s|repository: .*|repository: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE|" terraform/airflow-helm-values/values-dev.yaml
            sed -i "s|tag: .*|tag: $SHORT_SHA|" terraform/airflow-helm-values/values-dev.yaml
      
      - name: Commit changes to values.yaml
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add terraform/airflow-helm-values/values-dev.yaml
            git commit -m "Update image repository and tag in values-dev.yaml to $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            branch: ${{ github.head_ref }}